import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
const inter = Inter({ subsets: ["latin"] });

import { headers } from "next/headers";
import FourOhFour from "@/components/features/fourOhFour";
import Landing from "@/components/features/landing";
import GlobalStateSetter from "./_components/GlobalStateSetter";
const BASE_URL = process.env.BASE_URL || "";

export const metadata: Metadata = {
  title: "Resume Forge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, getUser } = getKindeServerSession();
  const authenticated = await isAuthenticated();
  const user = await getUser();

  const pathname = headers().get("pathname") || "/";

  function renderSwitchFeature() {
    switch (pathname) {
      case "/":
        return <Landing />;
      default:
        return <FourOhFour />;
    }
  }

  // if not authenticated, only allow landing page or 404
  // if (!authenticated) {
  //   // if not allowed, display 404
  //   return (
  //     <html lang="en">
  //       <body className={inter.className}>{renderSwitchFeature()}</body>
  //     </html>
  //   );
  // }

  const resumeData = (
    await fetch(`${BASE_URL}/api/resume/${user?.email}`).then(res => res.json())
  ).body;


  return (
    <html lang="en">
      <GlobalStateSetter
        isAuthenticated={authenticated}
        user={user}
        resumeData={resumeData}
      >
        <body className={inter.className}>{children}</body>
      </GlobalStateSetter>
    </html>
  );
}
