import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
const inter = Inter({ subsets: ["latin"] });

import { headers } from "next/headers";
import FourOhFour from "@/components/features/fourOhFour";

export const metadata: Metadata = {
  title: "Resume Forge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  landing,
}: Readonly<{
  children: React.ReactNode;
  landing: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();
  const authenticated = await isAuthenticated();

  const pathname = headers().get("pathname") || "/";

  const allowed = ["/"];

  if (!authenticated) {
    // if not allowed, display 404
    if (!allowed.includes(pathname)) {
      return (
        <html lang="en">
          <body className={inter.className}>
            <FourOhFour />
          </body>
        </html>
      );
    } else {
      return (
        <html lang="en">
          <body className={inter.className}>{landing}</body>
        </html>
      );
    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
