import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
const inter = Inter({ subsets: ["latin"] });

import { headers } from "next/headers";
import FourOhFour from "@/components/features/fourOhFour";
import Landing from "@/components/features/landing";

export const metadata: Metadata = {
  title: "Resume Forge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();
  const authenticated = await isAuthenticated();

  const pathname = headers().get("pathname") || "/";

  function renderSwitchFeature() {
    switch (pathname) {
      case "/":
        return <Landing />;
      default:
        return <FourOhFour />;
    }
  }

  // if not authenticated, only allow landing page or 404
  if (!authenticated) {
    // if not allowed, display 404
    return (
      <html lang="en">
        <body className={inter.className}>{renderSwitchFeature()}</body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
